allowBuilds:
  simple-git-hooks: true

autoInstallPeers: false

color: always

gitChecks: false

minimumReleaseAgeExclude:
  - '@typescript/*'
  - typescript

overrides:
  '@prettier/plugin-oxc': '-'

strictPeerDependencies: true

trustPolicy: no-downgrade

updateConfig:
  ignoreDependencies:
    - '@typescript/native-preview'
