allowBuilds:
  simple-git-hooks: true

autoInstallPeers: false

color: always

gitChecks: false

minimumReleaseAgeExclude:
  - '@standard-config/*'
  - '@typescript/*'
  - typescript

overrides:
  '@prettier/plugin-oxc': '-'

strictPeerDependencies: true

trustPolicy: no-downgrade
