name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/setup@v2.0.2
        with:
          runtime: node@24
      - run: pnpm stage publish --access=public --provenance
