name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: node@${{ matrix.node-version }} / typescript@7
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22
          - 24
          - latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/setup@v2.1.0
        with:
          cache: true
          runtime: node@${{ matrix.node-version }}
      - run: pnpm exec tsc --version
      - run: pnpm run '/^test:tsc:/'

  test-tsc6:
    name: node@${{ matrix.node-version }} / typescript@6
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22
          - 24
          - latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/setup@v2.1.0
        with:
          cache: true
          runtime: node@${{ matrix.node-version }}
      - run: pnpm exec tsc6 --version
      - run: pnpm run '/^test:tsc6:/'
