name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6.0.10
        with:
          cache: true
      - run: pnpm install
      - run: pnpm format:check
