name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/setup@v2.0.0
        with:
          cache: true
          runtime: node@24
      - run: pnpm format:check
